import { StyleSheet, Dimensions } from "react-native";
import { COLORS } from "../../../../../shared/constants";

export const styles = StyleSheet.create({
    overlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.6)",
        justifyContent: "center", 
        alignItems: "center",
    },
    container: {
        backgroundColor: "white",
        borderRadius: 30,
        padding: 25,
        width: 375,
        maxHeight: 709,
    },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: "700",
        color: "#000",
    },
    closeIcon: {
        fontSize: 18,
        color: "#000",
        padding: 5,
    },
    label: {
        fontSize: 16,
        fontWeight: "600",
        marginBottom: 8,
        color: "#333",
        marginTop: 10,
    },
    tagContainer: {
        marginVertical: 10,
    },
    tagList: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 10,
        marginBottom: 10,
    },
    tag: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        backgroundColor: COLORS.plum50 || "#F3E5F5",
        borderRadius: 12,
    },
    tagText: {
        color: "#51455D",
        fontSize: 14,
        fontWeight: "500",
    },
    addCircle: {
        width: 36,
        height: 36,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: "#000",
        justifyContent: "center",
        alignItems: "center",
    },
    contentInputContainer: {
        borderWidth: 1,
        borderColor: "#E5E5E5",
        borderRadius: 20,
        padding: 15,
        minHeight: 150,
        marginVertical: 15,
    },
    contentInput: {
        fontSize: 16,
        lineHeight: 24,
        color: "#333",
        minHeight: 120,
    },
    linkRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        marginBottom: 5,
    },
    input: {
        borderWidth: 1,
        borderColor: "#E5E5E5",
        borderRadius: 12,
        paddingHorizontal: 15,
        paddingVertical: 12,
        fontSize: 16,
        backgroundColor: "#fff",
        marginBottom: 10,
    },
    addCircleInline: {
        width: 34,
        height: 34,
        borderRadius: 17,
        borderWidth: 1,
        borderColor: "#000",
        justifyContent: "center",
        alignItems: "center",
    },
    plus: {
        fontSize: 22,
        fontWeight: "300",
        textAlign: "center",
    },
    imageWrapper: {
        width: "100%",
        aspectRatio: 4 / 3, 
        borderRadius: 20,
        overflow: "hidden",
        marginBottom: 15,
        position: "relative",
    },
    previewImageLarge: {
        width: "100%",
        height: "100%",
    },
    deletePhotoBtn: {
        position: "absolute",
        top: 8,
        right: 8,
        backgroundColor: "rgba(255,255,255,0.9)",
        borderRadius: 15,
        width: 28,
        height: 28,
        justifyContent: "center",
        alignItems: "center",
        zIndex: 10,
    },
    footer: {
        flexDirection: "row",
        justifyContent: "flex-end",
        alignItems: "center",
        marginTop: 20,
        paddingBottom: 20,
        gap: 12,
    },
    publishBtn: {
        backgroundColor: COLORS.plum || "#51455D",
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 30,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    publishBtnText: {
        color: "white",
        fontWeight: "600",
        fontSize: 16,
    },
});