import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    backgroundColor: "#fff",
    borderRadius: 28,
    width: "90%",
    maxHeight: "85%",
    padding: 24,
    position: "relative",
  },
  closeButton: {
    position: "absolute",
    top: 20,
    right: 20,
    zIndex: 10,
    padding: 4,
  },
  title: {
    fontSize: 32,
    fontWeight: "bold",
    textAlign: "center",
    color: "#111",
    marginBottom: 24,
    marginTop: 10,
  },
  label: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111",
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 14,
    paddingHorizontal: 16,
    height: 48,
    fontSize: 16,
    color: "#000",
    marginBottom: 20,
  },
  avatarSection: {
    alignItems: "center",
    marginBottom: 24,
  },
  groupAvatar: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#5C465A",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 14,
  },
  groupAvatarImage: {
    width: 70,
    height: 70,
    borderRadius: 35,
    marginBottom: 14,
  },
  groupAvatarText: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "bold",
  },
  photoButtonsRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 16,
  },
  photoButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  photoButtonText: {
    fontSize: 15,
    color: "#4A334A",
    fontWeight: "600",
  },
  participantsList: {
    maxHeight: 180,
    marginBottom: 20,
  },
  participantItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#F5F5F5",
  },
  participantInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  avatarText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  userName: {
    fontSize: 16,
    color: "#111",
    fontWeight: "500",
  },
  removeButton: {
    padding: 6,
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 10,
    gap: 12,
  },
  backButton: {
    borderWidth: 1,
    borderColor: "#4A334A",
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 22,
  },
  backButtonText: {
    color: "#4A334A",
    fontSize: 15,
    fontWeight: "600",
  },
  createButton: {
    backgroundColor: "#4A334A",
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 22,
  },
  disabledButton: {
    backgroundColor: "#A397A3",
    opacity: 0.7,
  },
  errorText: {
    color: "#FF3B30",
    fontSize: 13,
    marginBottom: 8,
    textAlign: "center",
  },
  createButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },
});
