import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    backgroundColor: "#fff",
    borderRadius: 24,
    width: "90%",
    maxHeight: "88%",
    padding: 22,
    position: "relative",
  },
  closeButton: {
    position: "absolute",
    top: 18,
    right: 18,
    zIndex: 10,
    padding: 4,
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    textAlign: "center",
    color: "#111",
    marginBottom: 20,
    marginTop: 8,
  },
  label: {
    fontSize: 15,
    fontWeight: "600",
    color: "#111",
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 14,
    paddingHorizontal: 16,
    height: 48,
    fontSize: 16,
    color: "#000",
    marginBottom: 18,
  },
  avatarSection: {
    alignItems: "center",
    marginBottom: 20,
  },
  groupAvatar: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#5C465A",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  groupAvatarImage: {
    width: 70,
    height: 70,
    borderRadius: 35,
    marginBottom: 12,
  },
  groupAvatarText: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "700",
  },
  photoButtonsRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 16,
  },
  photoButton: {
    paddingVertical: 4,
  },
  photoButtonText: {
    fontSize: 15,
    color: "#4A334A",
    fontWeight: "600",
  },
  removePhotoText: {
    fontSize: 15,
    color: "#FF3B30",
    fontWeight: "600",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 14,
    paddingHorizontal: 12,
    height: 44,
    marginBottom: 10,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: "#000",
    paddingVertical: 0,
  },
  usersList: {
    maxHeight: 220,
    marginBottom: 12,
  },
  userItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: "#F5F5F5",
  },
  userInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: 12,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  avatarText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  userName: {
    flex: 1,
    fontSize: 16,
    color: "#111",
    fontWeight: "500",
  },
  emptyText: {
    textAlign: "center",
    color: "#8E8E93",
    paddingVertical: 18,
  },
  errorText: {
    color: "#FF3B30",
    fontSize: 13,
    marginBottom: 8,
    textAlign: "center",
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
  },
  cancelButton: {
    borderWidth: 1,
    borderColor: "#4A334A",
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 22,
  },
  cancelButtonText: {
    color: "#4A334A",
    fontSize: 15,
    fontWeight: "600",
  },
  saveButton: {
    minWidth: 112,
    backgroundColor: "#4A334A",
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 22,
    alignItems: "center",
  },
  disabledButton: {
    backgroundColor: "#A397A3",
    opacity: 0.7,
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },
});
