import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    backgroundColor: "#fff",
    borderRadius: 28,
    width: "90%",
    maxHeight: "85%",
    padding: 24,
    position: "relative",
  },
  closeButton: {
    position: "absolute",
    top: 20,
    right: 20,
    zIndex: 10,
    padding: 4,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "center",
    color: "#0F0C1B",
    marginBottom: 20,
    marginTop: 10,
  },
  inputLabel: {
    fontSize: 14,
    color: "#111",
    fontWeight: "500",
    marginBottom: 6,
    paddingHorizontal: 4,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 14,
    paddingHorizontal: 14,
    height: 48,
    marginBottom: 20,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: "#000",
  },
  avatarSection: {
    alignItems: "center",
    marginBottom: 20,
  },
  groupAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 14,
  },
  groupAvatarText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
  photoActionsRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 16,
  },
  photoActionBtn: {
    flexDirection: "row",
    alignItems: "center",
  },
  actionIcon: {
    marginRight: 6,
  },
  photoActionText: {
    fontSize: 14,
    color: "#4A334A",
    fontWeight: "600",
  },
  participantsBox: {
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 16,
    padding: 16,
    maxHeight: 240,
  },
  participantsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  participantsTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111",
  },
  addParticipantBtn: {
    flexDirection: "row",
    alignItems: "center",
  },
  addParticipantText: {
    fontSize: 14,
    color: "#4A334A",
    fontWeight: "600",
  },
  participantsList: {
    flexGrow: 0,
  },
  userItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
  },
  userInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  avatarText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "600",
  },
  userName: {
    fontSize: 15,
    color: "#111",
    fontWeight: "500",
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 24,
    alignItems: "center",
  },
  backButton: {
    borderWidth: 1,
    borderColor: "#4A334A",
    borderRadius: 24,
    paddingVertical: 10,
    paddingHorizontal: 24,
    marginRight: 12,
  },
  backButtonText: {
    color: "#4A334A",
    fontSize: 15,
    fontWeight: "600",
  },
  saveButton: {
    backgroundColor: "#4A334A",
    borderRadius: 24,
    paddingVertical: 10,
    paddingHorizontal: 24,
  },
  disabledButton: {
    backgroundColor: "#A397A3",
    opacity: 0.7,
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },
});