import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: "#FAF8FF",
	},
	centered: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		paddingTop: 20,
	},
	scrollContent: {
		paddingHorizontal: 0,
		paddingBottom: 100,
		backgroundColor: "#FAF8FF",
	},
	listContent: {
		paddingHorizontal: 12,
		paddingBottom: 100,
		backgroundColor: "#FAF8FF",
	},
	sectionHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginTop: 14,
		marginBottom: 12,
	},
	sectionTitle: {
		fontSize: 15,
		color: "#070A1C",
	},
	seeAll: {
		fontSize: 15,
		color: "#4A354A",
	},
	blockFriends: {
		borderWidth: 1,
		borderColor: "#CDCED2",
		borderRadius: 6,
		width: "100%",
		paddingHorizontal: 12,
		paddingBottom: 12,
		marginTop: 12,
		backgroundColor: "#FFFFFF",
	},
	card: {
		backgroundColor: "#FFFFFF",
		borderRadius: 6,
		borderWidth: 1,
		borderColor: "#CDCED2",
		paddingHorizontal: 12,
		paddingTop: 16,
		paddingBottom: 12,
		alignItems: "center",
		marginBottom: 8,
	},
	profileButton: {
		alignItems: "center",
		width: "100%",
	},
	avatarContainer: {
		position: "relative",
		marginBottom: 14,
	},
	avatar: {
		width: 76,
		height: 76,
		borderRadius: 38,
	},
	statusIndicator: {
		position: "absolute",
		bottom: 1,
		right: 1,
		width: 19,
		height: 19,
		borderRadius: 9.5,
		backgroundColor: "#D1D1D6",
		borderWidth: 3,
		borderColor: "#FFFFFF",
	},
	name: {
		fontSize: 20,
		fontWeight: "700",
		marginBottom: 4,
		color: "#070A1C",
		textAlign: "center",
	},
	handle: {
		fontSize: 14,
		marginBottom: 14,
		color: "#070A1C",
		textAlign: "center",
	},
	buttonRow: {
		flexDirection: "row",
		gap: 10,
		flexWrap: "wrap",
		justifyContent: "center",
	},
	primaryBtn: {
		backgroundColor: "#4A354A",
		height: 34,
		paddingHorizontal: 15,
		borderRadius: 17,
		minWidth: 90,
		alignItems: "center",
		justifyContent: "center",
	},
	disabledBtn: {
		opacity: 0.6,
	},
	outlineBtn: {
		height: 34,
		paddingHorizontal: 15,
		borderRadius: 17,
		borderWidth: 1,
		borderColor: "#4A354A",
		minWidth: 90,
		alignItems: "center",
		justifyContent: "center",
	},
	primaryBtnText: {
		color: "#FFFFFF",
		fontSize: 12,
	},
	outlineBtnText: {
		color: "#4A354A",
		fontSize: 12,
	},
	emptyText: {
		color: "#6B6D7A",
		fontSize: 14,
		paddingVertical: 16,
		textAlign: "center",
	},
});
